### ISSUE TITLE
Base64 encoded emails are rejected by some SMTP servers

### ISSUE THREAD

**Issue by usommerl** [minosiants/pencil#16]
First of all, thank you for this excellent library! I've put it to good use in my current project. However, I've run into the following issue: Some intermediate SMTP servers reject the messages that were sent. The error message is `501 Syntax error - line too long`

I'm using `smtp.gmail.com` to send HTML messages, and the server always accepts the send request: `Code(250, Requested mail action okay, completed)`. Whether the email actually arrives in the recipient's inbox depends on the email service provider the recipient is using. The emails are successfully delivered if the recipients use `gmail.com` or `outlook.com`. One example where the messages are not delivered is when the recipient has an account with email service `gmx.de`. In such a case, the Google SMTP server sends a message delivery failure email to the senders inbox. This message contains the error code I have described above.

I've briefly scanned the `pencil` codebase yesterday, and I assume that it generates message bodies that do not comply with the `RFC2045` specification. Here is why:

- The message body is created in `Smtp.mimeBody` [\[1\]][1]
- This calls the `toBase64` method on the `Body` which essentially forwards the Base64 encoding to _scodecs_ `BitVector` [\[2\]][2]
- Depending on the body content, this will create a very long Base64 string without linebreaks
- This contradicts RFC2045 Section 6.8 - Base64 Content-Transfer-Encoding:

  _"The encoded output stream must be represented in lines of no more than 76 characters each."_ [\[3\]][3]

Please note that this is only an assumption and I might be totally wrong here. This is the _StackOverflow_ post that pointed me in this direction: [\[4\]][4]

[1]: https://github.com/minosiants/pencil/blob/6991ec6225f24a286d4f9fc8f404ab51da328015/src/main/scala/com/minosiants/pencil/Smtp.scala#L258
[2]: https://github.com/minosiants/pencil/blob/6991ec6225f24a286d4f9fc8f404ab51da328015/src/main/scala/com/minosiants/pencil/package.scala#L31
[3]: https://tools.ietf.org/html/rfc2045#section-6.8
[4]: https://stackoverflow.com/a/30781205/1827123

**Comment by minosiants** [comment]
@usommerl I added support for 76 bytes length. Could you have a look If it fix this issue.

**Comment by usommerl** [comment]
@minosiants: I'm happy to confirm that the issue is fixed in `v0.3.0`. Thanks a lot for your support!
