### ISSUE TITLE
String.getBytes should be avoided

### ISSUE THREAD

**Issue by hamnis** [minosiants/pencil#19]
That uses platform encoding, which may not be an ascii|utf8 compliant encoding.

`String.getBytes(Standardcharsets.UTF_8)` or `String.getBytes(Standardcharsets.US_ASCII)` should be preferred

**Comment by minosiants** [comment]
@hamnis I added [utf8 charset](https://github.com/minosiants/pencil/pull/18/commits/d0dc378f1a629c54d1da7956e1b1b7421784010a#diff-9cf4f6028fbe17640080a6b0c8d26256R33)

**Comment by hamnis** [comment]
@minosiants https://github.com/minosiants/pencil/blob/d0dc378f1a629c54d1da7956e1b1b7421784010a/src/main/scala/com/minosiants/pencil/package.scala#L35 and https://github.com/minosiants/pencil/blob/d0dc378f1a629c54d1da7956e1b1b7421784010a/src/main/scala/com/minosiants/pencil/package.scala#L37 
are still using the system charset

**Comment by minosiants** [comment]
@hamnis fixed
