### ISSUE TITLE
Let users provide their own logger

### ISSUE THREAD

**Issue by BalmungSan** [minosiants/pencil#27]
I think the best would be if this library only depends on `log4cats-core` and ask for users for an instance of a **Logger[F]**.

This way, the library wouldn't need to depend on `log4cats-slf4j` & `logback-classic` and wouldn't need to have a `logback.xml` file in the main resources.

**Comment by minosiants** [comment]
I use [io.chrisdavenport.log4cats.slf4j.Slf4jLogger](https://github.com/minosiants/pencil/blob/c4a8a85d2a6868672945af4fba3deb6b19f79848/src/main/scala/com/minosiants/pencil/SmtpSocket.scala#L51) for logger creation. I can remove `loback-classic`

**Comment by BalmungSan** [comment]
@minosiants while the removal of **logback** is good enough for me, I still believe the best is to allow users to pass their own logger when creating their `Client`, similar to how now we need to pass the `Blocker`, `SocketGroup` and `TlsContext`.

I will look into this latter today if you do not have any objection.

**Comment by minosiants** [comment]
@BalmungSan sure go for it.

**Comment by BalmungSan** [comment]
> @BalmungSan sure go for it.

Great :+1:

> Also could you run scalafmtAll to format code.

Oh right, I always forgot about it since I do not use it in my projects, will try to remember that.
