### ISSUE TITLE
Error using AWS SES.

### ISSUE THREAD

**Issue by maurogonzalez** [minosiants/pencil#41]
Hi there, 
Trying to use Pencil with AWS SES I found the following error `com.minosiants.pencil.data.Error$SmtpError`. After enabling DEBUG level in the logs configuration I found a `Getting Error: replies/code: 530 code does not exist` related to auth issues. Then I implemented another client and i found that the the following is being thrown `500,Syntax error, command unrecognized` by the following commands:
- Smtp.data\[F\]()
- Smtp.mail\[F\]()
- Smtp.rcpt\[F\]()
- Smtp.endEmail\[F\]()
- Smtp.quit\[F\]()
Removing those, emails are being sent. I don't know too much about SMTP and I'll do a deeper research.

**Comment by minosiants** [comment]
Hello @maurogonzalez I know this I've fixed this issue but haven't pushed it yet.  This error `530 SMTP authentication is required` . Which port are using to connect to smtp server ? try to use `25` if it is oppened

**Comment by minosiants** [comment]
@maurogonzalez  please check if you are still having it

**Comment by maurogonzalez** [comment]
@minosiants I'm using port 2587.
Using the javax-mail works fine and I was wondering why after removing from commands from the `SmtpClient` the emails are being sent.

**Comment by minosiants** [comment]
@maurogonzalez it impossible  that it works if you remove those commands because they construct an email. I have this issue  #24 may be they are related. I have to investigate.

**Comment by maurogonzalez** [comment]
Sorry, I confused some thing about the emails beaing sent.
PencilCode:

```
def smtpClient(cfg: AppConfiguration, blocker: Blocker)(implicit cs: ContextShift[IO]): Resource[IO, Client[IO]] = {
    val credentials = Credentials(Username(cfg.smtp.user.value), Password(cfg.smtp.password.value))
    SocketGroup[IO](blocker).evalMap { sg =>
      // cnfg.smtp.secure=true
      val tlsCtx = if (cfg.smtp.secure) TLSContext.system[IO](blocker) else TLSContext.insecure[IO](blocker)
      tlsCtx.map { tls =>
        Client[IO](cfg.smtp.host, cfg.smtp.port, Some(credentials))(blocker, sg, tls)
      }
    }
  }
  ```
  
  And javax-mail:
  ```
    def send(e: Email, smtpCfg: SmtpConfiguration) = {
    val props = System.getProperties
    props.put("mail.transport.protocol", "smtp")
    props.put("mail.smtp.port", smtpCfg.port)
    props.put("mail.smtp.starttls.enable", smtpCfg.secure.toString)
    props.put("mail.smtp.auth", "true")

    val body = e match {
      case Email.TextEmail(_, _, _, _, _, body) => body.map(_.value)
      case Email.MimeEmail(_, _, _, _, _, body, _, _) =>
        body.map {
          case Body.Ascii(value) => value
          case Body.Html(value)  => value
          case Body.Utf8(value)  => value
        }
    }

    val session = Session.getDefaultInstance(props);

    val msg = new MimeMessage(session)
    msg.setFrom(new InternetAddress(smtpCfg.fromEmail, smtpCfg.fromEmail))

    val recipients = e.recipients.map(r => new InternetAddress(r.address).asInstanceOf[Address]).toList.toArray
    msg.setRecipients(Message.RecipientType.TO, recipients)
    msg.setSubject(e.subject.map(_.value).getOrElse(""));
    msg.setContent(body.getOrElse(""), "text/html");

    val transport = session.getTransport();

    val _sendEmail = IO.fromTry(Try {
      transport.connect(smtpCfg.host, smtpCfg.user.value, smtpCfg.password.value)
      transport.sendMessage(msg, msg.getAllRecipients)
    })
    Resource.make(_sendEmail)(_ => IO(transport.close())).use(_ => IO.unit)
  }
  ```

**Comment by minosiants** [comment]
you shouldn't do this 
```val tlsCtx = if (cfg.smtp.secure) TLSContext.system[IO](blocker) else TLSContext.insecure[IO](blocker)```

it should be `TLSContext.system[IO](blocker)` and if `smtp server` support `tls` a mail's send using `tls` otherwise without it.

I would recommend you to run a simple code first form [Readme.md](https://github.com/minosiants/pencil#send-email) and if it works then tailor app in this way.

**Comment by maurogonzalez** [comment]
I ran the [example code](https://github.com/minosiants/pencil#send-email) and I got the same 530 error.

About the `Resource` I was trying to create a single `SmtpClient` to be used in the application just like another resource that lives within the life cycle (very similar as passing a SocketGroup from outside and creating an instance of `SmtpClient`)

**Comment by minosiants** [comment]
Ok I will look into it further. 
Are you using public or privet smtp server  ?

**Comment by maurogonzalez** [comment]
Public  from AWS SES, a couple of references:
- https://aws.amazon.com/premiumsupport/knowledge-center/ses-set-up-connect-smtp/
- https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-connect.html
Also if I found something, I added in the issue.

Thanks a lot @minosiants!

**Comment by minosiants** [comment]
@maurogonzalez I've found the bug. Fixing now 😄

**Comment by minosiants** [comment]
@maurogonzalez I've pushed it to `master`. Could you test it ?

**Comment by maurogonzalez** [comment]
@minosiants Just test it and works!!!
Looking at the logs, just saw the `Reply` with `Reply(Code(250,Requested mail action okay, completed),-,AUTH PLAIN LOGIN)`, the one you fixed. Thanks!

**Comment by minosiants** [comment]
I'm closing this
