### ISSUE TITLE
Text email with colon on first line results in empty email body

### ISSUE THREAD

**Issue by lukestewart13** [minosiants/pencil#50]
An email generated like this
```
val email = Email.text(
  From(...),
  To(...),
  Subject(...),
  Body.Ascii("foo: bar")
)
client.send(email)
```
results in an empty email message body because RFC822 interprets the body as a header. The workaround is to insert a newline before any body text that has a `:` on the first line:
```
val safeEmail = if (email.body.exists(_.value.takeWhile(_ != '\n').contains(':'))) {
  email.copy(body = email.body.map(b => Body.Ascii("\n" + b.value)))
} else {
  email
}
client.send(safeEmail)
```

**Comment by minosiants** [comment]
@lukestewart13  yes sending a empty line after headers fixed this problem.  Fixed now 😉 
thank you for reporting it

**Comment by minosiants** [comment]
fixed
